<?php

define('NEWS_TEASERS_COUNT', 3);

function site_news_block_info() {
	return array (
		'site_news_teasers' => array (
			'info' => t('News teasers block'),
		),
	);
}

function site_news_block_view($delta = '') {
	switch ($delta) {
		case 'site_news_teasers':
			return array('content' => nodes_views_by_type('news', variable_get('site_news_block_config', NEWS_TEASERS_COUNT)));
			break;
		default:
			return array('content' => '');
			break;
	}
}

function site_news_block_configure($delta = '') {
	return array ('site_news_block_config' => array (
		'#type' => 'select',
		'#title' => t('Teasers count'),
		'#description' => t('Count of news teasers in region'),
		'#default_value' => variable_get('site_news_block_config', NEWS_TEASERS_COUNT),
		'#options' => drupal_map_assoc(range(2, 10)),
	));
}

function site_news_block_save($delta = '', $edit = array()) {
  variable_set('site_news_block_config', $edit['site_news_block_config']);
}

function nodes_views_by_type($type, $limit = 5, $offset = 0) {
	$views = '';
	$nids = db_select('node', 'n')
		->fields('n', array('nid', 'created'))
		->condition('type', $type)
		->condition('status', 1)
		->orderBy('created', 'DESC')
		->range($offset, $limit)
		->addTag('node_access')
		->execute()
		->fetchCol();
	foreach ($nids as $nid) {
		$view = node_view(node_load($nid), 'teaser');
		$views.= drupal_render($view);
		
	}
	return $views;
}